### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by farleyknight**

### CODE REVIEW

**Comment by protoman** [comment]
The .pro is the real makefile for the project, it should not be placed under gitgnore.

**Comment by farleyknight** [comment]
I copied my previous comment on the issue from [here](https://github.com/protoman/rockbot/commit/5f1e70707a4eaff6ee380d59d1b2c13bf10e4197#commitcomment-13476985):

Could we possibly have different versions of `cpp_rockbot.pro` as separate files? Like say `cpp_rockbot.pro.linux` and `cpp_rockbot.pro.windows`. I just created a PR to fix the typo `cpp_rockbot.pro` in `.gitignore`. We can avoid merge conflicts in the future if we can stop tracking `cpp_rockbot.pro`, since this file [gets changed frequently](https://github.com/protoman/rockbot/commits/master/cpp_rockbot.pro).

**Comment by farleyknight** [comment]
Also since `Makefile` changes as often as we change OS's, it might make sense to stop tracking that as well. Every time I compile Linux git thinks I modified it, even though it's been added to `.gitignore`. I think the only way around that is to delete the `Makefile` in a commit.

**Comment by protoman** [comment]
Yeah, the Makefile should be removed, but the .pro should. Only exception
is Makefile.psp because I could not get the PSP build to work from the
qmake. It is very hard to do so, because it builds, but crashes, due to
some link not right.

## 

Iuri Fiedoruk, Software Developer

**Pull request closed without merging**
